### ISSUE TITLE
API

### ISSUE THREAD

**Issue by bilAlid** [nadeem-goolamhossen-dev/gestion-materiel#1]
Bonjour @nadeem-goolamhossen-dev 

Merci pour ce travail !
Pouvez-vous transformer le projet en mode "API" pour rester conforme à la consigne s'il vous plait ?

**Comment by nadeem-goolamhossen-dev** [comment]
Bonsoir @bilAlid ,

Pas de soucis pour tramsformer le projet en mode "API".

**Comment by nadeem-goolamhossen-dev** [comment]
Bonsoir @bilAlid ,

Vous pouvez revérifier le projet.
Merci
